from __future__ import annotations

import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WEB_APP = REPO_ROOT / "apps" / "web" / "app"


class TasksWorkspaceTests(unittest.TestCase):
    def test_tasks_page_mentions_long_run_configuration(self) -> None:
        content = (WEB_APP / "tasks" / "page.tsx").read_text(encoding="utf-8")
        self.assertIn("长期运行配置", content)
        self.assertIn("pause_after_consecutive_failures", content)
        self.assertIn("stale_sync_failure_threshold", content)
        self.assertIn("auto_pause_on_error", content)
        self.assertIn("review_limit", content)
        self.assertIn("comparison_run_limit", content)
        self.assertIn("长期运行参数", content)
        self.assertIn("失败后自动暂停", content)
        self.assertIn("告警强度", content)
        self.assertIn("人工接管原因", content)
        self.assertIn("恢复前先做什么", content)
        self.assertIn("focus_cards", content)
        self.assertIn("风险等级摘要", content)
        self.assertIn("恢复清单", content)
        self.assertIn("头号告警", content)
        self.assertIn("当前处理队列", content)
        self.assertIn("恢复检查项", content)
        self.assertIn("最早恢复时间", content)
        self.assertIn("接管复核截止", content)
        self.assertIn("severitySummary", content)
        self.assertIn("resumeChecklist", content)
        self.assertIn("执行安全门", content)
        self.assertIn("研究 / dry-run 候选池", content)
        self.assertIn("live 子集", content)
        self.assertIn("当前放行口径", content)
        self.assertIn("调度顺序矩阵", content)
        self.assertIn("失败规则矩阵", content)
        self.assertIn("失败阶段", content)
        self.assertIn("系统动作", content)
        self.assertIn("恢复前要看什么", content)
        self.assertIn("live_allowed_symbols", content)
        self.assertIn("live_max_stake_usdt", content)
        self.assertIn("live_max_open_trades", content)
        self.assertIn("同步失败细节", content)
        self.assertIn("人工接管时间线", content)
        self.assertIn("最近失败时间", content)
        self.assertIn("最近同步失败", content)
        self.assertIn("已接管多久", content)
        self.assertIn("cycle_cooldown_minutes", content)
        self.assertIn("max_daily_cycle_count", content)
        self.assertIn("自动化冷却时间", content)
        self.assertIn("每日最大轮次", content)
        self.assertIn("自动化运行参数", content)
        self.assertIn("long_run_seconds", content)
        self.assertIn("alert_cleanup_minutes", content)
        self.assertIn("长时间接管阈值", content)
        self.assertIn("活跃告警窗口", content)
        self.assertIn("长期运行与人工接管策略", content)
        self.assertIn("连续失败阈值", content)
        self.assertIn("同步陈旧阈值", content)
        self.assertIn("调度节奏", content)
        self.assertIn("人工接管复核", content)
        self.assertIn("接管快捷动作", content)
        self.assertIn("告警快捷处理", content)
        self.assertIn("确认头号告警", content)
        self.assertIn("清理非错误告警", content)
        self.assertIn("automation_confirm_alert", content)
        self.assertIn("automation_clear_non_error_alerts", content)
        self.assertIn("alert_id", content)
        self.assertIn("先人工接管", content)
        self.assertIn("只恢复到 dry-run", content)
        self.assertIn("确认后恢复自动化", content)
        self.assertIn("当前结论", content)
        self.assertIn("先不要恢复", content)
        self.assertIn("等待调度窗口", content)
        self.assertIn("恢复确认", content)
        self.assertIn("清单通过情况", content)
        self.assertIn("调度状态", content)
        self.assertIn("调度预览", content)
        self.assertIn("blockedReason", content)
        self.assertIn("nextRunAt", content)
        self.assertIn("takeoverReviewDueAt", content)
        self.assertIn("长期运行窗口", content)
        self.assertIn("这一轮之后还能不能继续自动跑", content)
        self.assertIn("今日轮次", content)
        self.assertIn("冷却剩余", content)
        self.assertIn("最近告警历史", content)
        self.assertIn("活跃告警", content)
        self.assertIn("首次出现", content)
        self.assertIn("最近一次出现", content)
        self.assertIn("重复次数", content)
        self.assertIn("告警处理建议", content)
        self.assertIn("头号告警怎么先处理", content)
        self.assertIn("最近发生了什么", content)
        self.assertIn("你现在该做什么", content)
        self.assertIn("当前先做什么", content)
        self.assertIn("恢复前还差什么", content)
        self.assertIn("现在先处理什么", content)
        self.assertIn("调度什么时候继续", content)
        self.assertIn("人工接管后怎么恢复", content)
        self.assertIn("最近复盘记录", content)
        self.assertIn("这里最多显示最近", content)


if __name__ == "__main__":
    unittest.main()
