const { test, expect } = require("@playwright/test");
const { getPlaywrightUseOptions } = require("./playwright-browser.cjs");
const { WEB_BASE_URL } = require("./test-urls.cjs");
const { loginAsAdmin } = require("./test-auth.cjs");

test.use(getPlaywrightUseOptions());

test("signals, strategies and tasks pages show automation summaries", async ({ page }) => {
  test.setTimeout(120000);
  const navigation = { waitUntil: "commit", timeout: 90000 };
  const renderTimeout = 60000;

  await loginAsAdmin(page, "/signals");
  await expect(page.locator("body")).toContainText("自动化入口", { timeout: renderTimeout });
  await expect(page.getByText("自动化入口")).toBeVisible();
  await expect(page.getByText("当前模式").first()).toBeVisible();
  await expect(page.getByText("下一步动作").first()).toBeVisible();

  await page.goto(`${WEB_BASE_URL}/strategies`, navigation);
  await expect(page.locator("body")).toContainText("策略主动作区", { timeout: renderTimeout });
  await expect(page.getByRole("button", { name: "处理自动化动作" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看执行器动作" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看研究链跳转" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看工具详情" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前执行器状态" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前候选可推进性" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前执行模式" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前账户收口摘要" })).toBeVisible();

  // 配置、候选池等细节已下沉到抽屉。
  await expect(page.getByText("当前配置摘要")).toHaveCount(0);
  await expect(page.getByText("执行安全门配置")).toHaveCount(0);
  await expect(page.getByText("自动化快捷入口")).toHaveCount(0);
  await expect(page.getByText("研究链入口")).toHaveCount(0);
  await expect(page.getByText("这些动作控制的是整台执行器")).toHaveCount(0);
  await page.getByRole("button", { name: "查看执行器动作" }).click();
  const strategyExecutionDrawer = page.getByRole("dialog", { name: "查看执行器动作" });
  await expect(strategyExecutionDrawer.getByRole("button", { name: "启动策略" })).toBeVisible();
  await expect(strategyExecutionDrawer.getByRole("button", { name: "暂停策略" })).toBeVisible();
  await expect(strategyExecutionDrawer.getByRole("button", { name: "停止策略" })).toBeVisible();
  await expect(strategyExecutionDrawer.getByRole("button", { name: "派发最新信号" })).toBeVisible();
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.getByRole("button", { name: "查看研究链跳转" }).click();
  const strategyRouteDrawer = page.getByRole("dialog", { name: "查看研究链跳转" });
  await expect(strategyRouteDrawer.getByRole("link", { name: "研究工作台" })).toBeVisible();
  await expect(strategyRouteDrawer.getByRole("link", { name: "回测工作台" })).toBeVisible();
  await expect(strategyRouteDrawer.getByRole("link", { name: "评估与实验中心" })).toBeVisible();
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();

  await page.goto(`${WEB_BASE_URL}/research`, navigation);
  await expect(page.locator("body")).toContainText("研究主动作区", { timeout: renderTimeout });
  await expect(page.getByRole("button", { name: "查看研究说明" })).toBeVisible();
  await page.getByRole("button", { name: "查看研究说明" }).click();
  const researchStoryDrawer = page.getByRole("dialog", { name: "查看研究说明" });
  await expect(researchStoryDrawer).toContainText("模型说明");
  await expect(researchStoryDrawer).toContainText("标签方式说明");
  await expect(researchStoryDrawer).toContainText("持有窗口说明");
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();

  await page.goto(`${WEB_BASE_URL}/backtest`, navigation);
  await expect(page.locator("body")).toContainText("成本模型说明", { timeout: renderTimeout });
  await expect(page.getByText("成本模型说明").first()).toBeVisible();
  await expect(page.getByText("当前回测选择").first()).toBeVisible();
  await expect(page.getByText("过滤参数目录").first()).toBeVisible();

  await page.goto(`${WEB_BASE_URL}/tasks`, navigation);
  await expect(page.locator("body")).toContainText("任务主动作区", { timeout: renderTimeout });
  await expect(page.getByRole("button", { name: "切换自动化模式" })).toBeVisible();
  await expect(page.getByRole("button", { name: "执行调度动作" })).toBeVisible();
  await expect(page.getByRole("button", { name: "处理告警动作" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看详情页跳转" })).toBeVisible();
  await expect(page.getByText("本轮自动化判断")).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前自动化模式" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前头号告警" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前人工接管状态" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前恢复建议" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "最近工作流摘要" })).toBeVisible();
  await expect(page.getByText("长期运行窗口")).toHaveCount(0);
  await expect(page.getByText("恢复自动化前先把这几项过一遍").first()).toHaveCount(0);
  await expect(page.getByText("调度什么时候继续", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "查看恢复详情" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看工作流详情" })).toBeVisible();
  await page.getByRole("button", { name: "执行调度动作" }).click();
  const dispatchDrawer = page.getByRole("dialog", { name: "执行调度动作" });
  await expect(dispatchDrawer.getByRole("button", { name: "运行自动化工作流" })).toBeVisible();
  await expect(dispatchDrawer.getByRole("button", { name: "暂停自动化" })).toBeVisible();
  await expect
    .poll(async () => (await dispatchDrawer.textContent()) ?? "", { timeout: renderTimeout })
    .toMatch(/Kill Switch|保持手动|切到手动|转人工接管/);
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.getByRole("button", { name: "处理告警动作" }).click();
  const alertDrawer = page.getByRole("dialog", { name: "处理告警动作" });
  await expect(alertDrawer.getByRole("button", { name: "确认头号告警" })).toBeVisible();
  await expect(alertDrawer.getByRole("button", { name: "清理非错误告警" })).toBeVisible();
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.getByRole("button", { name: "查看详情页跳转" }).click();
  const routeDrawer = page.getByRole("dialog", { name: "查看详情页跳转" });
  await expect(routeDrawer.getByRole("link", { name: "回到研究链" })).toBeVisible();
  await expect(routeDrawer.getByRole("link", { name: "去回测工作台" })).toBeVisible();
  await expect(routeDrawer.getByRole("link", { name: "去评估与实验中心" })).toBeVisible();
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.getByRole("button", { name: "查看工作流详情" }).click();
  const workflowDrawer = page.getByRole("dialog", { name: "工作流详情" });
  await expect(workflowDrawer).toContainText("长期运行配置");
  await expect(workflowDrawer).toContainText("调度顺序矩阵");
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();

  await page.goto(`${WEB_BASE_URL}/evaluation`, navigation);
  await expect(page.locator("body")).toContainText("评估主动作区", { timeout: renderTimeout });
  await expect(page.getByRole("heading", { name: "评估主动作区" })).toBeVisible();
  await expect(page.getByRole("button", { name: "更新阶段视图" })).toBeVisible();
  await expect(page.getByRole("button", { name: "更新实验对比" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看下一步跳转" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看评估配置" })).toBeVisible();
  await expect(page.getByRole("button", { name: "查看研究执行差异" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前推荐" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前阻塞" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "当前下一步动作" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "推荐摘要" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "淘汰摘要" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "准入预设", exact: true })).toHaveCount(0);
  await expect(page.getByText("最近复盘记录").first()).toHaveCount(0);
  await page.getByRole("button", { name: "查看下一步跳转" }).click();
  const evaluationRouteDrawer = page.getByRole("dialog", { name: "查看下一步跳转" });
  await expect(evaluationRouteDrawer.getByRole("link", { name: "去任务页看自动化" })).toBeVisible();
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.getByRole("button", { name: "查看评估配置" }).click();
  const configDrawer = page.getByRole("dialog", { name: "评估配置详情" });
  await expect(configDrawer).toContainText("准入门槛配置");
  await expect(configDrawer).toContainText("准入门槛目录");
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.goto(`${WEB_BASE_URL}/features`, navigation);
  await expect(page.locator("body")).toContainText("因子主动作区", { timeout: renderTimeout });
  await expect(page.getByRole("button", { name: "查看因子配置" })).toBeVisible();
  await page.getByRole("button", { name: "查看因子配置" }).click();
  const featuresConfigDrawer = page.getByRole("dialog", { name: "因子配置详情" });
  await expect(featuresConfigDrawer).toContainText("类别权重配置");
  await expect(featuresConfigDrawer).toContainText("趋势权重");
  await page.getByRole("button", { name: "关闭详情抽屉" }).click();
  await page.goto(`${WEB_BASE_URL}/tasks`, navigation);
  await page.getByRole("button", { name: "查看恢复详情" }).click();
  const recoveryDrawer = page.getByRole("dialog", { name: "恢复详情" });
  await expect(recoveryDrawer).toContainText("恢复检查项");
  await expect(recoveryDrawer).toContainText("失败规则矩阵");
});
